apiVersion: v1
kind: Namespace
metadata:
  name: bold-services
---
apiVersion: v1
kind: Secret
metadata:  
  name: bold-license-key
  namespace: bold-services
type: Opaque
stringData:
  #  The Bold BI licnece key which you have purchesed.
  BOLD_SERVICES_UNLOCK_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:  
  name: bold-user-secret
  namespace: bold-services
type: Opaque
stringData:
  # It should be a valid email.
  BOLD_SERVICES_USER_EMAIL: ""

  # It should meet our password requirements.
  BOLD_SERVICES_USER_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:  
  name: bold-db-secret
  namespace: bold-services
type: Opaque
stringData:
  # Type of database server can be used for configuring the Bold BI. Eg: mssql, mysql and postgresql
  BOLD_SERVICES_DB_TYPE: ""

  # Name of the Database Server
  BOLD_SERVICES_DB_HOST: ""

  # The system will use the following default port numbers based on the database server type.
  # PostgrSQL – 5234 and MySQL -3306
  # Please specify the port number for your database server if it is configured on a different port.
  # For MS SQL Server, this parameter is not necessary.
  BOLD_SERVICES_DB_PORT: ""

  # Username for the database server
  # Please refer to this documentation for information on the user's permissions.
  # https://help.boldbi.com/embedded-bi/faq/what-are-the-database-permissions-required-to-set-up-bold-bi-embedded/
  BOLD_SERVICES_DB_USER: ""

  # The database user's password
  BOLD_SERVICES_DB_PASSWORD: ""

  # If the database name is not specified, the system will create a new database called bold services.
  # If you specify a database name, it should already exist on the server.
  BOLD_SERVICES_DB_NAME: ""

  # For PostgreSQL DB Servers, this is an optional parameter.
  # The system will use the database name postgres by default.
  # If your database server uses a different default database, please provide it here.
  BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB: ""

  # If your database server requires additional connection string parameters, include them here
  # Connection string parameters can be found in the official document.
  # My SQL: https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html
  # PostgreSQL: https://www.npgsql.org/doc/connection-string-parameters.html
  # MS SQL: https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring
  # Note: A semicolon(;) should be used to separate multiple parameters.
  BOLD_SERVICES_DB_ADDITIONAL_PARAMETERS: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: branding-config
  namespace: bold-services
data:
  BOLD_SERVICES_BRANDING_MAIN_LOGO: ""
  
  BOLD_SERVICES_BRANDING_LOGIN_LOGO: ""
  
  BOLD_SERVICES_BRANDING_EMAIL_LOGO: ""
  
  BOLD_SERVICES_BRANDING_FAVICON: ""
  
  BOLD_SERVICES_BRANDING_FOOTER_LOGO: ""
  
  BOLD_SERVICES_SITE_NAME: ""
  
  BOLD_SERVICES_SITE_IDENTIFIER: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: bold-secret
  namespace: bold-services
type: Opaque
stringData:
  widget_bing_map_enable_secret: ""
  widget_bing_map_api_key_secret: ""
