{{- if eq .Values.loadBalancer.type "kong" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-ingress
  {{- include "boldbi.namespace" . | nindent 2 }}
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  ingressClassName: {{ .Values.loadBalancer.ingressClassName }}
  {{- if eq (split ":" .Values.appBaseUrl)._0 "https" }}
  tls:   
    {{- if .Values.loadBalancer.multipleHost }}
    {{- range $host := .Values.loadBalancer.multipleHost.hostArray }}
    - hosts:
      {{- range $dns := $host.hosts }}
        - {{ $dns }}
      {{- end }}
      secretName: {{ $host.secretName }}
    {{- end }}
    {{- else }}
    - hosts:
        - {{ (split "/" .Values.appBaseUrl)._2 }}
      secretName: {{ .Values.loadBalancer.singleHost.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.loadBalancer.multipleHost }}
    - http:
    {{- else }}
    - host: {{ (split "/" .Values.appBaseUrl)._2 }}
      http:
    {{- end }}
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: id-web-service
              port:
                number: 6000 
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: id-api-service
              port:
                number: 6001   
        - path: /ums
          pathType: Prefix
          backend:
            service:
              name: id-ums-service
              port:
                number: 6002   
        - path: /bi
          pathType: Prefix
          backend:
            service:
              name: bi-web-service
              port:
                number: 6004 
        - path: /bi/api
          pathType: Prefix
          backend:
            service:
              name: bi-api-service
              port:
                number: 6005
        - path: /bi/jobs
          pathType: Prefix
          backend:
            service:
              name: bi-jobs-service
              port:
                number: 6006
        - path: /bi/designer
          pathType: Prefix
          backend:
            service:
              name: bi-dataservice-service
              port:
                number: 6007
        - path: /boldetl/
          pathType: Prefix
          backend:
            service:
              name: bold-etl-service
              port:
                number: 6009
        - path: /reporting
          pathType: Prefix
          backend:
            service:
              name: reports-web-service
              port:
                number: 6550
        - path: /reporting/api
          pathType: Prefix
          backend:
            service:
              name: reports-api-service
              port:
                number: 6551
        - path: /reporting/jobs
          pathType: Prefix
          backend:
            service:
              name: reports-jobs-service
              port:
                number: 6552
        - path: /reporting/viewer
          pathType: Prefix
          backend:
            service:
              name: reports-viewer-service
              port:
                number: 6554  
        - path: /reporting/reportservice
          pathType: Prefix
          backend:
            service:
              name: reports-reportservice-service
              port:
                number: 6553             
{{- end }}
