apiVersion: v1
kind: PersistentVolume
metadata:
  name: bold-fileserver
  namespace: bold-services
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: <FileSystemOCID>:<MountTargetIP>:<path>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bold-fileserver-claim
  namespace: bold-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: bold-fileserver