apiVersion: v1
kind: Secret
metadata:
  name: bold-secret
  namespace: bold-services
type: Opaque
stringData:
  widget_bing_map_enable_secret: ""
  widget_bing_map_api_key_secret: ""
  #Integrating Azure Application Insights with Bold BI Enterprise Edition enables you to track and visualize your application’s performance, detect issues, and enhance your application’s overall reliability.
  application_insights_connection_string_secret: ""
