apiVersion: v1
kind: Secret
metadata:
  name: bold-secret
  namespace: bold-services
type: Opaque
stringData:
  widget_bing_map_enable_secret: ""
  widget_bing_map_api_key_secret: ""
  application_insights_connection_string_secret: "InstrumentationKey=2b71599d-be81-4902-a3f0-901cdb13c103;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=abdc9495-5ca8-498d-9987-001b00148a1a"
