apiVersion: v1
kind: Secret
metadata:  
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-license-key
{{ include "boldbi.namespace" . | indent 2 }}
type: Opaque
stringData:
  BOLD_SERVICES_UNLOCK_KEY: "{{ .Values.licenseKeyDetails.licenseKey }}"
  