apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-secret
  {{- if eq $.Release.Namespace "default" }}
  namespace: {{ $.Values.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
type: Opaque
stringData:
  widget_bing_map_enable_secret: "{{ $.Values.bingMapWidget.enabled }}"
  widget_bing_map_api_key_secret: "{{ $.Values.bingMapWidget.apiKey }}"