# Default values for boldbi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appBaseUrl: ''
optionalLibs: 'mongodb,mysql,influxdb,snowflake,oracle,google,clickhouse'
clusterProvider: 'eks'

namespace:
  name: bold-services
  annotations: {}
  labels: {}

persistentVolume:
  # persistent volumes were global resources. 
  # so if you already have Bold BI installed in your cluster, then the previous persistent volume name will conflict with current installation.
  # Change this name to avoid conflicts with previous Bold BI persistent volumes.
  name: bold-fileserver
  capacity: 3Gi
  eks:
    efsFileSystemId: ''

image:
  idRepo: gcr.io/boldbi-294612
  biRepo: gcr.io/boldbi-294612
  reportsRepo: gcr.io/boldreports
  # Overrides the image tag whose default is the chart appVersion.
  idTag: 6.6.12
  biTag: 6.6.12
  reportsTag: 5.1.20
  pullPolicy: IfNotPresent
imagePullSecrets: []

versions:
  idp: "4.5.1"
  bi: "6.6.12"
  reports: "5.1.20"

loadBalancer:
  type: alb
  groupName: 'bold-services'
  affinityCookie:
    enable: true
    affinityCookieExpiration: 600 
  ssl:
    enable: true
    tls: arn
    arn: ''
  singleHost: 
    secretName: bold-tls

instanceConfig:
  - app: id-web
    product: boldid
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: id-api
    product: boldid
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: id-ums
    product: boldid
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-web
    product: boldbi
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-api
    product: boldbi
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-jobs
    product: boldbi
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-dataservice
    product: boldbi
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: reports-web
    product: boldreports
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: reports-api
    product: boldreports
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: reports-jobs
    product: boldreports
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: reports-viewer
    product: boldreports
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: reports-reportservice
    product: boldreports
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
    
service:
  type: ClusterIP
  port: 80
  
autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    stabilizationWindowSeconds: 60
    podsValue: 1
    podsPeriodSeconds: 60
    percentValue: 10
    percentPeriodSeconds: 60
    
bingMapWidget:
  # Specify the existing bingMap Secret Name. The default is 'bold-secret'
  bingMapSecretName: ''
  enabled: false
  apiKey: ''